#!/bin/bash
# Script de verificacion para el escenario DNS spoofing

echo "======================================================================="
echo "  VERIFICACION DEL ESCENARIO DNS SPOOFING"
echo "======================================================================="
echo ""

echo "[1] Verificando servidor DNS..."
echo ""
echo "Estado de dnsmasq:"
ps aux | grep dnsmasq | grep -v grep
echo ""
echo "Puerto 53 en uso:"
netstat -tulpn 2>/dev/null | grep :53 || ss -tulpn | grep :53
echo ""

echo "[2] Probando resolucion DNS directa..."
echo ""
echo "nslookup www.banco.com 10.0.0.53:"
nslookup www.banco.com 10.0.0.53
echo ""
echo "dig @10.0.0.53 www.banco.com +short:"
dig @10.0.0.53 www.banco.com +short 2>/dev/null || echo "dig no disponible"
echo ""

echo "[3] Verificando /etc/resolv.conf..."
echo ""
cat /etc/resolv.conf
echo ""

echo "[4] Verificando /etc/hosts..."
echo ""
cat /etc/hosts | grep -E "banco|example|legitimo"
echo ""

echo "[5] Verificando servidores web..."
echo ""
echo "Servidor LEGITIMO (10.0.0.80):"
curl -s http://10.0.0.80 2>/dev/null | grep -i "legitimo\|10.0.0.80" || echo "No responde"
echo ""
echo "Servidor FALSO (10.0.0.99):"
curl -s http://10.0.0.99 2>/dev/null | grep -i "falso\|10.0.0.99" || echo "No responde"
echo ""

echo "[6] Probando resolucion completa..."
echo ""
echo "curl http://www.banco.com:"
curl -v http://www.banco.com 2>&1 | head -20
echo ""

echo "======================================================================="
echo "  COMANDOS DE PRUEBA MANUAL"
echo "======================================================================="
echo ""
echo "# Probar DNS directamente:"
echo "nslookup www.banco.com 10.0.0.53"
echo "dig @10.0.0.53 www.banco.com"
echo ""
echo "# Acceder por IP (siempre funciona):"
echo "curl http://10.0.0.80"
echo "curl http://10.0.0.99"
echo ""
echo "# Acceder por nombre (requiere DNS funcionando):"
echo "curl http://www.banco.com"
echo ""
echo "# Forzar uso de DNS especifico:"
echo "host www.banco.com 10.0.0.53"
echo ""
echo "======================================================================="
echo "  SOLUCION SI NO RESUELVE DOMINIOS"
echo "======================================================================="
echo ""
echo "OPCION 1: Usar IP directamente"
echo "  curl http://10.0.0.80  (sitio legitimo)"
echo "  curl http://10.0.0.99  (sitio falso)"
echo ""
echo "OPCION 2: Verificar que dnsmasq esta corriendo"
echo "  ps aux | grep dnsmasq"
echo "  Si no esta: dnsmasq -C /tmp/dns_legitimo.conf &"
echo ""
echo "OPCION 3: Usar /etc/hosts como respaldo"
echo "  echo '10.0.0.80 www.banco.com' >> /etc/hosts"
echo ""
echo "OPCION 4: Probar con nslookup directo"
echo "  nslookup www.banco.com 10.0.0.53"
echo ""
echo "======================================================================="
